#!/usr/bin/env python3
"""The firmware's LVGL settings for the browser build: CONFIG_LV_* lines of an ESP-IDF sdkconfig -> lv_kconfig.h.

    python web/emu/gen_lv_kconfig.py build/v55/sdkconfig > web/emu/lv_kconfig.h

LVGL reads them as under ESP-IDF (lv_conf_kconfig.h includes LV_CONF_KCONFIG_EXTERNAL_INCLUDE). Changed for the
browser: the heap is the C library's (no PSRAM, no lvgl_mem.c). Rerun after changing LVGL options in sdkconfig.defaults.
"""
import re
import sys

OVERRIDE = {
    'CONFIG_LV_USE_CUSTOM_MALLOC': None,          # main/lvgl_mem.c is ESP-only
    'CONFIG_LV_USE_CLIB_MALLOC': '1',
    'CONFIG_LV_USE_STDLIB_MALLOC': '1',          # (9.2 derives it; listed for newer versions)
}

out = ['// Generated by web/emu/gen_lv_kconfig.py from the firmware\'s sdkconfig: the LVGL settings of the display.',
       '#pragma once', '#define CONFIG_LV_CONF_SKIP 1']
seen = set()
for line in open(sys.argv[1], encoding='utf-8'):
    m = re.match(r'^(CONFIG_LV_[A-Z0-9_]+)=(.*)$', line.strip())
    if not m:
        continue
    k, v = m.groups()
    if k in OVERRIDE:
        continue
    v = '1' if v == 'y' else v
    out.append(f'#define {k} {v}')
    seen.add(k)
for k, v in OVERRIDE.items():
    if v is not None:
        out.append(f'#define {k} {v}')
print('\n'.join(out))
